// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASXJfcwwKnJJ2RN_d6jNFYah9StzNkz8Y',
    appId: '1:790390962830:web:bb4e469344395dd5e067df',
    messagingSenderId: '790390962830',
    projectId: 'loginapp-462c6',
    authDomain: 'loginapp-462c6.firebaseapp.com',
    storageBucket: 'loginapp-462c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY7Dgz59gwbpjiu2welpbbJekboKhVqbc',
    appId: '1:790390962830:android:63e9236ca3e3a490e067df',
    messagingSenderId: '790390962830',
    projectId: 'loginapp-462c6',
    storageBucket: 'loginapp-462c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM4W249nls6DIMlmpEZ3X4k7dSH-0N_3Y',
    appId: '1:790390962830:ios:988570ae03031b69e067df',
    messagingSenderId: '790390962830',
    projectId: 'loginapp-462c6',
    storageBucket: 'loginapp-462c6.appspot.com',
    iosBundleId: 'com.example.simpleSigninSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM4W249nls6DIMlmpEZ3X4k7dSH-0N_3Y',
    appId: '1:790390962830:ios:988570ae03031b69e067df',
    messagingSenderId: '790390962830',
    projectId: 'loginapp-462c6',
    storageBucket: 'loginapp-462c6.appspot.com',
    iosBundleId: 'com.example.simpleSigninSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASXJfcwwKnJJ2RN_d6jNFYah9StzNkz8Y',
    appId: '1:790390962830:web:f30f24037bbfb56fe067df',
    messagingSenderId: '790390962830',
    projectId: 'loginapp-462c6',
    authDomain: 'loginapp-462c6.firebaseapp.com',
    storageBucket: 'loginapp-462c6.appspot.com',
  );

}